# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b66924294086d76085b87cfacd6ddd3df92edc60b8667989eba6b0a4d67208d2d90e93c794c55350d6f6acfc076595df4a2d848a303ba0d0c770dd00f05fc90

test:
  secret_key_base: d3ba45cea30697df192512d6135fcec3f35727d3a7ba826b71648662d64d7c45d5f2555ed12815b4b09beebe9c58ec610ef593581f1b849020a6b0b609cf243a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
